<?php

namespace WorkShopBundle\Repository;

/**
 * FrescoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FrescoRepository extends \Doctrine\ORM\EntityRepository
{
}
