<?php

namespace WorkShopBundle\Repository;

/**
 * HumainDefinitionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HumainDefinitionRepository extends \Doctrine\ORM\EntityRepository
{
}
