<?php

namespace WorkShopBundle\Repository;

/**
 * PaintingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaintingRepository extends \Doctrine\ORM\EntityRepository
{
}
