<?php

namespace WorkShopBundle\Repository;

/**
 * WorkShopRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkShopRepository extends \Doctrine\ORM\EntityRepository
{
}
